name: find_your_doctor_application
description: UI of a Mobile Application intended for finding nearby Doctors.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  smooth_star_rating_nsafe: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
